// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	ID        string `bson:"_id"`
	Text      string `bson:"text"`
	Completed bool   `bson:"completed"`
	UserID    string `bson:"userId"`
}

type User struct {
	ID       string `bson:"_id"`
	Username string `bson:"username"`
	Email    string `bson:"email"`
}
