// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	Text      string `json:"text"`
	Completed bool   `json:"completed"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	UserID    string `json:"userId"`
}

type User struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type CreateTodoInput struct {
	Text      string `json:"text"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UpdateTodoInput struct {
	Text      *string `json:"text,omitempty"`
	Completed *bool   `json:"completed,omitempty"`
}
